"""cria tabela Prova

Revision ID: 05c3f03c2200
Revises: 01ab21951e98
Create Date: 2024-12-04 15:28:34.794394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c3f03c2200'
down_revision = '01ab21951e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(15), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.Column('idProf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProf'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prova_data_hora_fim'), ['data_hora_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_prova_data_hora_inicio'), ['data_hora_inicio'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prova_data_hora_inicio'))
        batch_op.drop_index(batch_op.f('ix_prova_data_hora_fim'))

    op.drop_table('prova')
    # ### end Alembic commands ###
