"""Recriando tabela professor

Revision ID: 46df5735e2a3
Revises: 
Create Date: 2024-12-03 17:50:09.108915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46df5735e2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professor_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_name'))

    op.drop_table('professor')
    # ### end Alembic commands ###
