"""Alterar índice na coluna enunciado

Revision ID: 897cfda5fc83
Revises: b9fd78181f31
Create Date: 2024-12-04 20:27:26.501939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897cfda5fc83'
down_revision = 'b9fd78181f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prova_data_hora_fim'), ['data_hora_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_prova_data_hora_inicio'), ['data_hora_inicio'], unique=False)

    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questao_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questao_tipo'))

    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prova_data_hora_inicio'))
        batch_op.drop_index(batch_op.f('ix_prova_data_hora_fim'))

    # ### end Alembic commands ###
