"""cria tabela Questao

Revision ID: b9fd78181f31
Revises: 05c3f03c2200
Create Date: 2024-12-04 20:17:52.465572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fd78181f31'
down_revision = '05c3f03c2200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('idProva', sa.Integer(), nullable=True),
    sa.Column('idProf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProf'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['idProva'], ['prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questao_enunciado'), ['enunciado'], unique=False)
        batch_op.create_index(batch_op.f('ix_questao_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questao_tipo'))
        batch_op.drop_index(batch_op.f('ix_questao_enunciado'))

    op.drop_table('questao')
    # ### end Alembic commands ###
